# Generated by Django 5.0.1 on 2024-01-20 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='is_indivisual',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Client_Sales_Bridge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.company')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sales')),
            ],
        ),
        migrations.CreateModel(
            name='DateProductTotalSales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Client_DateProductTotalSales_Bridge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.company')),
                ('dts_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.dateproducttotalsales')),
            ],
        ),
        migrations.CreateModel(
            name='DateTotalSales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Client_DateTotalSales_Bridge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.company')),
                ('dts_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.datetotalsales')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTotalSales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Client_ProductTotalSales_Bridge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.company')),
                ('dts_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.producttotalsales')),
            ],
        ),
        migrations.CreateModel(
            name='TotalSales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Client_TotalSales_Bridge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.company')),
                ('ts_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.totalsales')),
            ],
        ),
    ]
